Repository JIgorSilva/MercadinhoApp, pull requests merged in 2025-01, with the labels that each got.

#20 Api funcao alterar produto
  app/src/main/java/com/igor/mercadinho/app/controller/ProdutoController.java
  app/src/main/java/com/igor/mercadinho/app/exception/ProductWithDifferentIdentifier.java
  app/src/main/java/com/igor/mercadinho/app/exception/ProdutoNameNotExistsException.java
  app/src/main/java/com/igor/mercadinho/app/services/ProdutosService.java
Labels: enhancement

#23 Fix(api produtos services task 13)
  app/src/main/java/com/igor/mercadinho/app/services/ProdutosService.java
Labels: bug

#24 Fix(api configuracao pomxml task 14)
  .vscode/launch.json
  app/pom.xml
Labels: bug

#25 Feat(api test produto service test task 15)
  app/src/test/java/com/igor/mercadinho/app/servicesTest/ProdutoServiceTest.java
Labels: enhancement

#26 fix(Refatorando metodos da Service)
  app/src/main/java/com/igor/mercadinho/app/services/ProdutosService.java
Labels: bug

#27 fix(Correção configuração de ambiente e dependencias para Teste)
  .vscode/launch.json
  app/pom.xml
Labels: bug

#28 feat(Criação dos testes unitarios e de integração com mock da Services)
  app/src/test/java/com/igor/mercadinho/app/servicesTest/ProdutoServiceTest.java
Labels: enhancement

#33 feat(testando metodo buscarProdutosId exception)
  app/src/test/java/com/igor/mercadinho/app/servicesTest/ProdutoServiceTest.java
Labels: test

#36 Test(api test produto service test task 18)
  app/src/main/java/com/igor/mercadinho/app/controller/ProdutoController.java
  app/src/main/java/com/igor/mercadinho/app/services/ProdutosService.java
  app/src/test/java/com/igor/mercadinho/app/servicesTest/ProdutoServiceTest.java
Labels: test

#38 Deploy(api produção produto deploy fly io task 19)
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  app/.dockerignore
  app/.gitignore
  app/.mvn/wrapper/MavenWrapperDownloader.java
  app/.mvn/wrapper/maven-wrapper.jar
  app/.mvn/wrapper/maven-wrapper.properties
  app/Dockerfile
  app/fly.toml
  app/mvnw
  app/mvnw.cmd
  app/pom.xml
  app/src/test/java/com/igor/mercadinho/app/servicesTest/ProdutoServiceTest.java
Labels: bug
